name: Release

on:
  push:
    paths:
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - android: "android15"
            kernel: "6.6"

    steps:
      - name: Initialize and Sync Kernel Source
        run: |
          sudo apt update -y && sudo apt install -y repo
          repo init --depth 1 -u https://android.googlesource.com/kernel/manifest -b common-${{ matrix.android }}-${{ matrix.kernel }}
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)

      - name: Add KernelSU
        working-directory: common
        run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v1.0.5

      - name: Checkout SUSFS
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu -b gki-${{ matrix.android }}-${{ matrix.kernel }}
          cd susfs4ksu

          case "${{ matrix.android }}-${{ matrix.kernel }}" in
            "android15-6.6")
              susfs_commit="0ed9845a3f6ed624d55484384f2b414a7527fc3b"
            ;;
          esac

          git checkout ${susfs_commit}

      - name: Apply SUSFS Patches
        working-directory: common
        run: |
          cp ../susfs4ksu/kernel_patches/fs/* fs
          cp ../susfs4ksu/kernel_patches/include/linux/* include/linux
          patch -p1 < ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ matrix.android }}-${{ matrix.kernel }}.patch
          cd KernelSU
          patch -p1 < ../../susfs4ksu/kernel_patches
